<?php

class Point3D extends Point2D
{
    protected float $z;
    private array $xyz;
    public function __construct(float $x, float $y, float $z)
    {
        parent::__construct($x, $y);
        $this->z = $z;
    }

    public function __toString()
    {
        return "This is Point3D"; // TODO: Change the autogenerated stub
    }

    /**
     * @return float
     */
    public function getZ(): float
    {
        return $this->z;
    }

    /**
     * @param float $z
     */
    public function setZ(float $z): void
    {
        $this->z = $z;
    }

    public function setXYZ(float $x, float $y, float $z){
        $this->xyz = array($x,$y,$z);
    }

    public function getXYZ() {
        return $this->xyz;
    }
}