<?php
include_once "Circle.php";

class Cylinder extends Circle
{
    public int $height;

    public function __construct($radius, $color, $height)
    {
        parent::__construct($radius, $color);
        $this->height = $height;
    }

    public function getArea()
    {
        return 2*pi()*$this->radius*($this->radius+$this->height); // TODO: Change the autogenerated stub
    }

    public function getCapacity(){
        return $this->height * pow($this->radius,2);
    }

    public function __toString()
    {
        return parent::__toString()  ."height: " .$this->height; // TODO: Change the autogenerated stub
    }
}